import turtle
print("Добрий день")
turtle.speed(3)
turtle.color("blue")
turtle.forward(150)
turtle.left(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(150)
turtle.left(90)
turtle.forward(80)
turtle.left(90)